/**
 * Ed25519 license verification using Web Crypto (works in both browser preview
 * and Node/Electron main via globalThis.crypto). The public key is embedded in
 * the app; the private key lives ONLY on the vendor's machine (see
 * scripts/license-generator.mjs). Payloads are base64url JSON + base64url sig
 * joined by a dot, prefixed with "MB1.".
 *
 * Format: MB1.<b64url(payload)>.<b64url(signature)>
 */
import { AppError, LicenseError } from "./errors";

export interface LicensePayload {
  customer: string;
  company: string;
  machineId: string;
  type: "trial" | "subscription" | "lifetime" | "enterprise";
  issuedAt: string;   // ISO
  expiresAt?: string; // ISO — omit for lifetime/enterprise
  features: string[]; // e.g. ["pos","reports","backup"]
  nonce: string;      // random per-key
}

/**
 * Vendor public key (Ed25519, SPKI DER, base64url).
 * Generated by: node scripts/license-generator.mjs keygen
 * Private key is stored in ~/.managbyte/keys/private.pem — never commit it.
 */
export const VENDOR_PUBLIC_KEY_B64URL =
  "MCowBQYDK2VwAyEAYsdoBtBTbCmncDg5imOvExikCT--DVsR6gqMWjcWnTA";

const b64urlToBytes = (s: string): Uint8Array => {
  const pad = s.length % 4 === 0 ? "" : "=".repeat(4 - (s.length % 4));
  const b64 = (s + pad).replace(/-/g, "+").replace(/_/g, "/");
  const bin = atob(b64);
  const out = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
  return out;
};

const bytesToB64url = (b: Uint8Array): string => {
  let bin = "";
  for (let i = 0; i < b.length; i++) bin += String.fromCharCode(b[i]);
  return btoa(bin).replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/, "");
};

export const encodePayload = (p: LicensePayload): string =>
  bytesToB64url(new TextEncoder().encode(JSON.stringify(p)));

/** Parse and cryptographically verify a license string. Throws LicenseError. */
export async function verifyLicense(
  licenseString: string,
  currentMachineId: string,
  publicKeyB64Url: string = VENDOR_PUBLIC_KEY_B64URL,
): Promise<LicensePayload> {
  // ── Electron: delegate to main process (Node.js crypto — Ed25519 reliable).
  //    Public key is hardcoded in main.cjs — do NOT pass it from renderer.
  const api = typeof window !== "undefined" && (window as any).electronAPI;
  if (api?.verifyLicenseKey) {
    const result = await api.verifyLicenseKey(licenseString, currentMachineId);
    if (!result.ok) throw new LicenseError(result.error ?? "Échec de la vérification de la licence");
    return result.payload as LicensePayload;
  }

  // ── Browser fallback: Web Crypto ──
  if (!licenseString?.startsWith("MB1.")) {
    throw new LicenseError("Format de clé de licence invalide");
  }
  const parts = licenseString.slice(4).split(".");
  if (parts.length !== 2) throw new LicenseError("Clé de licence corrompue");

  const [payloadB64, sigB64] = parts;
  const payloadBytes = b64urlToBytes(payloadB64);
  const sigBytes    = b64urlToBytes(sigB64);

  let key: CryptoKey;
  try {
    const spki = b64urlToBytes(publicKeyB64Url);
    key = await crypto.subtle.importKey(
      "spki", spki.buffer as ArrayBuffer,
      { name: "Ed25519" }, false, ["verify"],
    );
  } catch (e) {
    throw new AppError("LICENSE_KEY", "Clé publique non supportée dans cet environnement", 500, e);
  }

  const valid = await crypto.subtle.verify(
    { name: "Ed25519" }, key,
    sigBytes.buffer as ArrayBuffer,
    payloadBytes.buffer as ArrayBuffer,
  );
  if (!valid) throw new LicenseError("Signature de licence invalide - peut être falsifiée");

  let payload: LicensePayload;
  try {
    payload = JSON.parse(new TextDecoder().decode(payloadBytes));
  } catch {
    throw new LicenseError("Contenu de la licence illisible");
  }

  // machineId "*" = developer/wildcard license (for testing only)
  if (payload.machineId !== "*" && payload.machineId !== currentMachineId) {
    throw new LicenseError("Cette licence est liée à un autre appareil");
  }
  if (payload.expiresAt && new Date(payload.expiresAt).getTime() < Date.now()) {
    throw new LicenseError("La licence a expiré");
  }
  return payload;
}

/**
 * Stable machine fingerprint.
 * Electron : delegated to getMachineId() in seed.ts which calls the main process.
 * Browser  : random ID persisted in localStorage.
 * NOTE: This function is kept for backward compatibility. Prefer getMachineId()
 * from @/lib/seed everywhere in the UI.
 */
export async function getMachineId(): Promise<string> {
  // In Electron: sync call through window.electronAPI
  if (typeof window !== "undefined" && (window as any).electronAPI?.getMachineIdSync) {
    return (window as any).electronAPI.getMachineIdSync() as string;
  }
  const KEY = "managbyte-machine-id-v1";
  let existing = localStorage.getItem(KEY);
  if (!existing) {
    const buf = new Uint8Array(16);
    crypto.getRandomValues(buf);
    existing = Array.from(buf).map((b) => b.toString(16).padStart(2, "0")).join("").toUpperCase();
    localStorage.setItem(KEY, existing);
  }
  return existing;
}
